### ISSUE TITLE
documentation for quick start

### ISSUE THREAD

**Issue by yyz1989** [peterjohnlawrence/com.inova8.odata2sparql.v2#37]
Hi, 

Thanks a lot for the great work. I would like to try this software, but I am not able to get it running properly. Would you like to provide any hint on it? 

I investigated your technical documentation "ODATA2SPARQL.v4" for help, where there is a chapter "HOW TO USE ODATA2SPARQL", but I was not able to sort out a correct step by step process to correctly set up a running server on top of the sample dataset "NorthWind". 

The installation is easy, because it is just a WAR file which has to be deployed into Tomcat. Then the configuration process is a bit complicated. At step 1a, it says "On startup OData2SPARQL attempts to locate a remote repository which will contain the definitions of the datasets to be published", but I don't know how I can tell OData2SPARQL where is that remote repository. Then at step 1b, "If no remote repository is located, OData2SPARQL will instead search the local folder within the Tomcat folder: ...\WEB-INF\classes\repositories\", apparently there will be no local repository if the server is created for the first time. So there is only step 1c available, which is "If no local repository is located, OData2SPARQL will use the default files located in this directory
including models.ttl to initialize a local repository." But according to Tomcat log, it actually looks for file "/var/opt/inova8/odata2sparql/models.ttl", so I copied your sample model  https://github.com/peterjohnlawrence/com.inova8.odata2sparql.v2/blob/master/odata2sparql.v2/src/main/resources/repositories/models.ttl to that location, imported other relevant RDF data into an RDF4J server, and adjusted "models.ttl" a bit to use the RDF4J server containing the data. Then the OData2SPARQL server seems to start. Is this correct? Then what is the next step? How should I provide the EDM of NorthWind to OData2SPARQL?

Thank you very much for the help.

Best regards,
Yang

**Comment by peterjohnlawrence** [comment]
Sorry about the inaccurate documentation. I recently changed the location of the models.ttl and missed changing all references. You have the correct location. The reason for this change is so one can have multiple odata2sparql serves running simultaneously each with different models.ttl and repositories.

<<How should I provide the EDM of NorthWind to OData2SPARQL?>>

You need a triplestore containing the RDF that you want to publish. You could load Northwind data and model located here as a test case:  https://github.com/peterjohnlawrence/com.inova8.northwind Then define the SPARQL endpoints in the models.ttl that tell OData2sparql where to find the data and vocabulary as follows:


Data and Vocabulary Repositories
When configuring an OData2sparql service, the configuration requires two repositories to be defined (they can be the same) for each endpoint to be published:
•	Data Repository: this is the repository that contains all of the data, and will be the repository queried by an OData request. If no Vocabulary repository is defined, then this is also the repository from which the OData $metadata model will be inferred. The inference of the $metadata will search all of the triples for any declared classes and properties to be published. 
•	Vocabulary Repository: this is the repository from which the OData $metadata model will be inferred using the queries defined in the OData4sparql.rdf. Since this Vocabulary Repository can be distinct from the data repository, and indeed be hosted in an entirely separate triple store if required. The Vocabulary repository needs to declare the following:
o	RDFS/OWL Classes which are mapped to OData entitypes and entitysets.
o	RDFS/OWL Data properties which are mapped to OData properties.
o	RDFS/OWL Object properties which are mapped to OData navigation properties and association sets.
o	SPIN templates which are mapped to OData function imports or operations.
Thus it is possible to tailor the model that is published via the OData $metadata by what is defined in the Vocabulary Repository

I hope this helps.

**Comment by yyz1989** [comment]
Hi Peter,

Thanks a lot for the quick response. What I did was as follows:

1. Setup rdf4j 2.2.4 with tomcat 8.5
2. Deploy odata2sparqlv2.war into tomcat
3. Create a repository in rdf4j workbench named "test"
4. Import files "data v1, model v2, operations v3" into graph <http://inova8.com/odata4sparql/models>, resulting in 34852 triples
5. Start tomcat and the exception is like
```
23:23:13.550 [http-nio-8080-exec-2] ERROR c.i.o.RdfRepository.RdfRepositories - Cannot access /var/opt/inova8/odata2sparql/models.ttl Check it is located in correct directory and is visible
java.io.FileNotFoundException: /var/opt/inova8/odata2sparql/models.ttl
```
6. Create a service description file named "models.ttl" based on your test model file with the following content and place it under /var/opt/inova8/odata2sparql/

```
# baseURI: http://inova8.com/odata4sparql/models
# imports: http://inova8.com/odata4sparql

@prefix : <http://inova8.com/odata4sparql/models#> .
@prefix odata4sparql: <http://inova8.com/odata4sparql#> .
@prefix openrdf: <http://www.openrdf.org#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rep: <http://www.openrdf.org/config/repository#> .
@prefix sparql: <http://www.openrdf.org/config/repository/sparql#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

odata4sparql:FOAF
  rdf:type odata4sparql:Prefix ;
  odata4sparql:namespace <http://xmlns.com/foaf/0.1/> ;
  odata4sparql:prefix "foaf"^^xsd:string ;
.
odata4sparql:OEXT
  rdf:type odata4sparql:Prefix ;
  odata4sparql:namespace <http://oracle.com/semtech/jena-adaptor/ext/function#> ;
  odata4sparql:prefix "OEXT"^^xsd:string ;
.
odata4sparql:ORACLE_SEM_FS_NS
  rdf:type odata4sparql:Prefix ;
  odata4sparql:namespace <http://oracle.com/semtech#timeout=100,qid=123> ;
  odata4sparql:prefix "ORACLE_SEM_FS_NS"^^xsd:string ;
.
odata4sparql:OUEXT
  rdf:type odata4sparql:Prefix ;
  odata4sparql:namespace <http://oracle.com/semtech/jena-adaptor/ext/user-def-function#> ;
  odata4sparql:prefix "OUEXT"^^xsd:string ;
.
<http://inova8.com/odata4sparql/models>
  rdf:type owl:Ontology ;
  owl:imports <http://inova8.com/odata4sparql> ;
.
:FN
  rdf:type odata4sparql:Prefix ;
  odata4sparql:namespace <http://www.w3.org/2005/xpath-functions#> ;
  odata4sparql:prefix "FN"^^xsd:string ;
.
:NWD
  rdf:type odata4sparql:Prefix ;
  odata4sparql:namespace <http://northwind.com/> ;
  odata4sparql:prefix "NWD"^^xsd:string ;
.

:NW
  rdf:type odata4sparql:Dataset ;
  rdf:type odata4sparql:Prefix ;
  odata4sparql:dataRepository :NW_Data ;
  odata4sparql:datasetPrefix odata4sparql:FOAF ;
  odata4sparql:datasetPrefix odata4sparql:OWL ;
  odata4sparql:datasetPrefix odata4sparql:RDFS ;
  odata4sparql:datasetPrefix odata4sparql:SKOS ;
  odata4sparql:datasetPrefix :NW ;
  odata4sparql:datasetPrefix :NWD ;
  odata4sparql:defaultPrefix :NW ;
  odata4sparql:namespace <http://northwind.com/model/> ;
  odata4sparql:prefix "northwind"^^xsd:string ;
  odata4sparql:vocabularyRepository :NW_Vocabulary ;
  odata4sparql:withRdfAnnotations "false"^^xsd:boolean ;
  odata4sparql:withSapAnnotations "false"^^xsd:boolean ;
  odata4sparql:useBaseType "false"^^xsd:boolean ;
  rdfs:label "Northwind"^^xsd:string ;
.

:NW_Data
  rdf:type rep:Repository ;
  rep:repositoryID "NW_Data"^^xsd:string ;
  rep:repositoryImpl :NW_Data_Impl ;
  rdfs:label "NW Data"^^xsd:string ;
.
:NW_Data_Impl
  rdf:type openrdf:SPARQLRepository ;
  odata4sparql:defaultQueryLimit 10000 ;
  odata4sparql:sparqlProfile odata4sparql:SPARQL11 ;
  rep:repositoryType openrdf:SPARQLRepository ;
  sparql:query-endpoint <http://localhost:8080/rdf4j-server/repositories/test?default-graph-uri=http://northwind.com/model/> ;
  sparql:update-endpoint <http://localhost:8080/rdf4j-server/repositories/test?default-graph-uri=http://northwind.com/model/> ;
  rdfs:label "NW Data Impl"^^xsd:string ;
.
:NW_Vocabulary
  rdf:type rep:Repository ;
  rep:repositoryID "NW_Vocabulary"^^xsd:string ;
  rep:repositoryImpl :NW_Vocabulary_Impl ;
  rdfs:label "NW Vocabulary"^^xsd:string ;
.
:NW_Vocabulary_Impl
  rdf:type openrdf:SPARQLRepository ;
  odata4sparql:sparqlProfile odata4sparql:SPARQL11 ;
  rep:repositoryType openrdf:SPARQLRepository ;
  sparql:query-endpoint <http://localhost:8080/rdf4j-server/repositories/test?default-graph-uri=http://northwind.com/model/> ;
  sparql:update-endpoint <http://localhost:8080/rdf4j-server/repositories/test?default-graph-uri=http://northwind.com/model/> ;
  rdfs:label "NW Vocabulary Impl"^^xsd:string ;
.
```

7. The odata service seems to be up, according to logs
```
23:29:44.475 [http-nio-8080-exec-2] INFO  c.i.o.Constants.RdfConstants - Models.ttl location:/var/opt/inova8/odata2sparql/models.ttl
23:29:44.479 [http-nio-8080-exec-2] INFO  c.i.o.Constants.RdfConstants - Support ontologies location:/usr/local/tomcat/webapps/odata2sparqlv2/WEB-INF/classes/ontologies/
23:29:44.488 [http-nio-8080-exec-2] INFO  c.i.o.RdfRepository.RdfRepositories - Repository loaded from /var/opt/inova8/odata2sparql
23:29:45.310 [http-nio-8080-exec-2] INFO  c.i.o.RdfRepository.RdfRepositories - Dataset loaded: http://inova8.com/odata4sparql/models#NW
23:29:45.360 [http-nio-8080-exec-2] INFO  c.i.o.RdfRepository.RdfRepositories - Dataset loaded: http://inova8.com/odata4sparql#ODATA2SPARQL
```
If I get http://localhost:8080/odata2sparqlv2/ I can receive response
```
<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<code/>
<message xml:lang="en">The URL is too short.</message>
</error>
```
Then I tried to get a resource with http://localhost:8080/odata2sparqlv2/NW/Customer?$top=1, but I got an error, and the log says:
```
23:41:48.506 [http-nio-8080-exec-9] INFO  c.i.o.RdfODataServiceFactory - GET: http://localhost:8080/odata2sparqlv2/NW/Customer?$top=1
23:41:48.506 [http-nio-8080-exec-9] INFO  c.i.o.RdfModel.RdfModelProvider - Loading model NW from endpoint: http://localhost:8080/rdf4j-server/repositories/test?default-graph-uri=http://northwind.com/model/
23:41:48.527 [http-nio-8080-exec-9] INFO  c.i.o.RdfModel.RdfModelProvider - 0 Classes found []
23:41:48.537 [http-nio-8080-exec-9] INFO  c.i.o.RdfModel.RdfModelProvider - 0 Datatypes found []
23:41:48.564 [http-nio-8080-exec-9] INFO  c.i.o.RdfModel.RdfModelProvider - 0 DataTypeProperties_Domains found []
23:41:48.564 [http-nio-8080-exec-9] ERROR c.i.o.S.SparqlODataSingleProcessors - Error getting rdfEdmProvider  for rdfRepositoryID:NW
23:41:48.565 [http-nio-8080-exec-9] ERROR c.i.o.RdfODataErrorCallback - org.apache.olingo.odata2.api.exception.ODataException:Cannot create SparqlODataSingleProcessor for rdfRepositoryId:NW
```

What did I miss here?

Thank you very much for the help.

Best regards,
Yang

**Comment by peterjohnlawrence** [comment]
<<If I get http://localhost:8080/odata2sparqlv2/ I can receive response>>

Since odata2sparql can support multiple odata endpoints simultaneously, the URL needs the identifier of the particular repository, in this case NW. So the URL

`http://localhost:8080/odata2sparql.v2/NW`
 
will return the published entitySets

`http://localhost:8080/odata2sparql.v2/NW/$metadata`

will return the full metadata

`http://localhost:8080/odata2sparql.v2/NW/Customer`

will return all Customer entity types

<<Then I tried to get a resource with http://localhost:8080/odata2sparqlv2/NW/Customer?$top=1, but I got an error, and the log says:>>

Although the endpoint can connect to your triple store, the SPARQLendpoint does not  seem to contain any valid data. 

In your description you say that you imported everything into the graph 

`http://inova8.com/odata4sparql/models`

but the URI of the SPARQLendpoint specified in models.ttl is using a default graph of

`http://northwind.com/model/`

I would suggest that you either:

- Change the models.ttl to refer to the graphs that you have created
- OR Change the triplestore so that all of your test data is in the `http://northwind.com/model/` graph

Because odata2sparql can publish multiple endpoints from the same triplestore, each of which is defined by a different repository with different graphs, these problems can occur. Odata2sparql is not simply publishing the entire triplestore.

I hope this helps

**Comment by yyz1989** [comment]
Hi Peter,

Thanks a lot for the hint! Yes, that is the key! Indeed I overlooked the graph name. I adapted that and now everything just works like a charm!

So is the EDM metadata directly created from the ontology "northwind.model.v2.rdf"? If I want to publish another RDF dataset as Odata, what I need to do is just define the ontology properly, right?

Another question in terms of odata2sparql v4, is it usable or still under development? It says "in progress" on your Website, but I am wondering if it is because of Apache Olingo, since its support to Odata 4.0 is indeed in progress.

Thank you again for the great work.

Best regards, 
Yang

**Comment by peterjohnlawrence** [comment]
> If I want to publish another RDF dataset as Odata, what I need to do is just define the ontology properly, right?

Yes and give it a different identifier, other than NW. To define the ontology 'properly' it is best to declare the classes as owl:Classes, and the properties as either owl:ObjectProperty or owl:DatatypeProperty with the appropriate domains and ranges.

> Another question in terms of odata2sparql v4, is it usable or still under development?

It is usable certainly for querying. The insert, update, and deletes (especially the nested inserts) are not fully functional. Simple inserts and deletes work. Unfortunately OdataV4 was a complete rewrite.

**Comment by peterjohnlawrence** [comment]
BTW the models TTL allows the 'vocabulary' repository, the repository from which the EDM is deduced, to be different from the 'data' repository, the repository that is queried when executing an OData request. However they can be the same.

**Comment by yyz1989** [comment]
Hi Peter,

Thanks a lot for the pointers. All clear now. Will investigate further.

Have a nice day.

Best regards,
Yang
